import { SSTIM, SSTIM_EX, SSTIM_V } from '../../rdf/namespaces.js'
import { applicationRoute } from '../../config/applicationUrls.js'

const TRACK_SEMANTICS = {
  BinauralBeat: {
    label: 'Binaural Beat',
    kind: 'Audio voice type',
    uri: SSTIM('BinauralVoice').value,
    description: 'Two carrier tones presented dichotically so their frequency difference defines the perceived beat target.',
  },
  IsochronicTone: {
    label: 'Isochronic Tone',
    kind: 'Audio voice type',
    uri: SSTIM('SymmetryVoice').value,
    description: 'A pulsed tone mode represented in the ontology as the isochronous case of SymmetryVoice.',
  },
  Carrier: {
    label: 'Carrier',
    kind: 'Audio voice type',
    uri: SSTIM('Voice').value,
    description: 'A direct audio layer used as a carrier tone or continuous voice component in a patch.',
  },
  Noise: {
    label: 'Noise',
    kind: 'Audio voice type',
    uri: SSTIM('Voice').value,
    description: 'A broadband noise layer (white, pink, or brown) shaped by a filter, used for masking and calming textures.',
  },
  Drone: {
    label: 'Drone',
    kind: 'Audio voice type',
    uri: SSTIM('Voice').value,
    description: 'A sustained pad built from a stack of detuned oscillators for a lush, slowly beating continuous tone.',
  },
  Sample: {
    label: 'Sample',
    kind: 'Audio voice type',
    uri: SSTIM('Voice').value,
    description: 'A looping ambient field recording (synthetic CC0 soundscape) layered as a continuous background voice.',
  },
  // These point at sstim:ControlTrack, not at the catalog voice classes they
  // used to name. A control track is silent — it modulates other tracks — while
  // sstim:MartigliVoice and sstim:SymmetryVoice are audible layers of a catalog
  // preset. Linking a silent modulator to an audible voice was the category
  // error ADR 0041 removed along with the names (see LEGACY_CONTROL_TYPES).
  LFO: {
    label: 'LFO',
    kind: 'Control signal type',
    uri: SSTIM('ControlTrack').value,
    description: 'A low-frequency oscillation used to drive slow auditory or cross-modal changes. In the breathing range it is what makes a patch Martigli-shaped — the technique follows from the parameters, not from the name.',
  },
  Permutation: {
    label: 'Permutation',
    kind: 'Control signal type',
    uri: SSTIM('ControlTrack').value,
    description: 'A repeated sequence signal whose order is generated by a permutation, used for rhythmic or attentional entrainment.',
  },
  Geometry: {
    label: 'Geometry',
    kind: 'Visual track type',
    uri: SSTIM_V('modalityVisual').value,
    description: 'A visual sensory modality component rendered as structured geometry.',
  },
  Particles: {
    label: 'Particles',
    kind: 'Visual track type',
    uri: SSTIM_V('modalityVisual').value,
    description: 'A visual sensory modality component rendered as moving particles.',
  },
  Gradient: {
    label: 'Gradient',
    kind: 'Visual track type',
    uri: SSTIM_V('modalityVisual').value,
    description: 'A visual sensory modality component rendered as a changing gradient field.',
  },
  Blink: {
    label: 'Blink',
    kind: 'Visual track type',
    uri: SSTIM_V('modalityVisual').value,
    description: 'A photic visual component that flashes on and off at a set rate and duty cycle, supporting flicker-based entrainment.',
  },
  Oscillate: {
    label: 'Oscillate',
    kind: 'Visual track type',
    uri: SSTIM_V('modalityVisual').value,
    description: 'A visual component whose brightness and scale vary smoothly and sinusoidally at a set rate.',
  },
  Pacer: {
    label: 'Pacer',
    kind: 'Visual track type',
    uri: SSTIM_V('modalityVisual').value,
    description: 'A breathing-pacer orb that expands and contracts at a slow rate to guide paced breathing.',
  },
  Ripple: {
    label: 'Ripple',
    kind: 'Visual track type',
    uri: SSTIM_V('modalityVisual').value,
    description: 'Concentric rings expanding outward at a set cadence, suited to breath- or pulse-synchronised guidance.',
  },
  Spiral: {
    label: 'Spiral',
    kind: 'Visual track type',
    uri: SSTIM_V('modalityVisual').value,
    description: 'A rotating radial sweep producing continuous optical motion.',
  },
  Mandala: {
    label: 'Mandala',
    kind: 'Visual track type',
    uri: SSTIM_V('modalityVisual').value,
    description: 'Symmetric overlaid polygons that rotate, pairing naturally with the Symmetry control.',
  },
  // ADR 0046 colour and spatial sources. They are visual tracks like the nine
  // above; without explicit entries they fell through semanticForTrackType's
  // generic fallback and reported sstim:Voice, an *audio* class, in the
  // semantic panel and in the graph deep link it builds.
  ColorField: {
    label: 'Colour Field',
    kind: 'Visual track type',
    uri: SSTIM_V('modalityVisual').value,
    description: 'A full-stage colour wash of authored on/off colours, optionally alternating at a safety-clamped blink rate.',
  },
  DepthMarkers: {
    label: 'Depth Markers',
    kind: 'Visual track type',
    uri: SSTIM_V('modalityVisual').value,
    description: 'A marker and grid recipe placed in neutral 3D scene space, used to make stereoscopic depth legible.',
  },
  TreeScene: {
    label: 'Tree Scene',
    kind: 'Visual track type',
    uri: SSTIM_V('modalityVisual').value,
    description: 'A deterministic branching-tree recipe feeding the shared stereoscopic scene contract.',
  },
  AbstractScene: {
    label: 'Abstract Scene',
    kind: 'Visual track type',
    uri: SSTIM_V('modalityVisual').value,
    description: 'A deterministic abstract composition (Miro, Kandinsky, or Klee styling) feeding the shared stereoscopic scene contract.',
  },
  LandscapeScene: {
    label: 'Landscape Scene',
    kind: 'Visual track type',
    uri: SSTIM_V('modalityVisual').value,
    description: 'A deterministic landscape recipe with day, dusk, or night palette, feeding the shared stereoscopic scene contract.',
  },
  Vibration: {
    label: 'Vibration',
    kind: 'Haptic track type',
    uri: SSTIM_V('modalitySomatosensory').value,
    description: 'A somatosensory modality component represented as vibration or haptic pulse delivery.',
  },
}

// Closed registry (KR-17): the third element is a fully resolved IRI that must
// be declared in the live ontology modules, or null when no genuine term
// exists yet. Never derive an IRI from a parameter name — semantic.test.js
// checks every non-null entry against the parsed ontology.
const PARAM_SEMANTICS = {
  gain: ['Gain', 'Amplitude parameter', SSTIM('initialVolume').value, 'Voice output amplitude for this layer.'],
  pan: ['Pan', 'Spatial parameter', SSTIM('panPosition').value, 'Stereo placement from left to right.'],
  frequency: ['Frequency', 'Frequency parameter', SSTIM('baseFrequency').value, 'Base or carrier frequency in Hz.'],
  pulseRate: ['Pulse rate', 'Rhythmic parameter', SSTIM('pulseRateHz').value, 'Rate of rhythmic pulses in Hz.'],
  noteDurationFrac: ['Note duration', 'Envelope parameter', SSTIM('noteDurationFraction').value, 'Fraction of each pulse occupied by the active note envelope.'],
  leftFreq: ['Left carrier frequency', 'Frequency parameter', SSTIM('carrierFreqLeft').value, 'Left-ear carrier frequency for binaural presentation.'],
  rightFreq: ['Right carrier frequency', 'Frequency parameter', SSTIM('carrierFreqRight').value, 'Right-ear carrier frequency for binaural presentation.'],
  centerFreq: ['Center frequency', 'Frequency parameter', SSTIM('baseFrequency').value, 'Center frequency around which binaural carriers are arranged.'],
  beatFreq: ['Beat frequency', 'Rhythmic parameter', SSTIM('beatHz').value, 'Difference frequency of a binaural beat.'],
  periodSec: ['Period', 'Timing parameter', SSTIM('breathingPeriodInitial').value, 'Initial cycle period for a breathing or control oscillation.'],
  targetPeriodSec: ['Target period', 'Timing parameter', SSTIM('breathingPeriodFinal').value, 'Final cycle period reached by a breathing or control oscillation.'],
  inhaleRatio: ['Inhale ratio', 'Timing parameter', SSTIM('breathingPhaseRatio').value, 'Fraction of a breathing cycle assigned to the inhale phase.'],
  amplitude: ['Amplitude', 'Control parameter', SSTIM('breathingAmplitude').value, 'Control signal depth or excursion.'],
  rateHz: ['Rate', 'Rhythmic parameter', SSTIM('pulseRateHz').value, 'Control or sequence step rate in Hz.'],
  nnotes: ['Note count', 'Sequence parameter', SSTIM('noteCount').value, 'Number of notes or sequence positions in a Symmetry cycle.'],
  noctaves: ['Octave span', 'Pitch parameter', SSTIM('octaveSpan').value, 'Pitch span covered by a Symmetry sequence.'],
  cutoff: ['Cutoff', 'Filter parameter', null, 'Filter cutoff / centre frequency in Hz applied to a broadband noise source.'],
  resonance: ['Resonance', 'Filter parameter', null, 'Filter resonance (Q) of the noise shaping filter.'],
  detune: ['Detune', 'Pitch parameter', null, 'Detune spread in cents across a drone oscillator stack.'],
  rotationSpeed: ['Rotation speed', 'Visual parameter', SSTIM('rotationSpeed').value, 'Visual rotation rate or angular speed.'],
  sides: ['Sides', 'Visual parameter', SSTIM('visualSideCount').value, 'Number of sides used by a geometric visual form.'],
  density: ['Density', 'Visual parameter', SSTIM('visualDensity').value, 'Density of rendered visual elements.'],
  blinkRate: ['Blink rate', 'Visual parameter', SSTIM_EX('hasFlickerRateHz').value, 'Photic flicker rate in Hz for a blinking visual.'],
  duty: ['Duty cycle', 'Visual parameter', SSTIM_EX('hasDutyCycle').value, 'On-fraction of each blink cycle.'],
  oscRate: ['Oscillation rate', 'Visual parameter', null, 'Rate in Hz of a smooth visual oscillation.'],
  intensity: ['Intensity', 'Haptic parameter', SSTIM('stimulationIntensity').value, 'Strength of haptic or sensory output.'],
  pattern: ['Pattern', 'Haptic parameter', SSTIM('hapticPattern').value, 'Pattern index or selector for haptic delivery.'],
}

export function semanticForTrackType(type) {
  return TRACK_SEMANTICS[type] ?? {
    label: type ?? 'Track type',
    kind: 'Track type',
    uri: SSTIM('Voice').value,
    description: 'A patch track type used by Patch Studio.',
  }
}

export function semanticForParameter(_track, paramName) {
  const match = PARAM_SEMANTICS[paramName]
  if (!match) {
    // Explicitly unmapped: never mint an sstim IRI from a parameter name.
    return {
      label: paramName,
      kind: 'Patch parameter',
      uri: null,
      description: 'A Patch Studio parameter with no ontology term yet.',
    }
  }
  const [label, kind, uri, description] = match
  return { label, kind, uri, description }
}

// Exported for the mapping-registry test only.
export const KNOWN_TRACK_TYPES = Object.keys(TRACK_SEMANTICS)
export const KNOWN_PARAMETERS = Object.keys(PARAM_SEMANTICS)

export function localSemanticName(uri) {
  return uri?.split(/[#/]/).pop() ?? ''
}

// The knowledge browser lives at /graph/ and resolves the fragment on arrival
// (OntologyGraph.resolveHashToNodeId). Point straight at it. The older `/#term`
// form only worked because the entrance forwards a stray hash, which costs a
// redirect hop at the origin root and leaves the deployment entirely under a
// project-page mount, where `/` belongs to the owner site rather than to us.
export function semanticGraphHref(info) {
  const local = localSemanticName(info?.uri)
  const route = applicationRoute('/graph/')
  return local ? `${route}#${encodeURIComponent(local)}` : route
}
