/**
 * The named-graph invariant, enforced.
 *
 * CLAUDE.md §5.5 and §8: annotation data lives in named graphs and never in the
 * default graph, because the default graph holds authoritative ontology data.
 * Until this file existed nothing checked it — `annotationRdf.js` emitted eight
 * quads with no test of any kind beside it, so dropping the graph argument from
 * a `quad(...)` call would have passed `make test`, `make check` and
 * `make validate` while silently merging user annotations into the
 * authoritative graph.
 *
 * That failure is quiet and close to unrecoverable after the fact, which is why
 * these assert the property directly rather than through a snapshot: a snapshot
 * would have to be regenerated by whoever broke it, and would be.
 *
 * The visibility boundary is tested in the same file because it fails the same
 * way — silently, into a graph that gets published.
 */

import { describe, expect, it } from 'vitest'
import { annotationsToQuads, safeVisibility } from './annotationRdf.js'

const PUBLIC_GRAPH = 'https://w3id.org/sstim/implementation/bsclab/annotation/public'
const ANNOTATION_BASE = 'https://w3id.org/sstim/implementation/bsclab/annotation/'

const record = (overrides = {}) => ({
  id: 'a1',
  userId: 'user-1',
  targetIri: 'https://w3id.org/sstim#Preset',
  annotationText: 'A note.',
  annotationType: 'commenting',
  visibility: 'private',
  createdAt: '2026-08-17T10:00:00.000Z',
  updatedAt: '2026-08-17T11:00:00.000Z',
  ...overrides,
})

describe('annotation RDF — the named-graph invariant', () => {
  it('places every quad in a named graph, never the default graph', async () => {
    const quads = await annotationsToQuads([
      record(),
      record({ id: 'a2', visibility: 'public' }),
      record({ id: 'a3', userId: 'user-2', visibility: 'unrecognised-value' }),
    ])

    expect(quads.length).toBeGreaterThan(0)
    for (const q of quads) {
      // N3/rdf-js signals the default graph as a DefaultGraph term whose value
      // is the empty string. Both checks, because either alone can pass on a
      // malformed term.
      expect(q.graph.termType).not.toBe('DefaultGraph')
      expect(q.graph.value).not.toBe('')
      expect(q.graph.value.startsWith(ANNOTATION_BASE)).toBe(true)
    }
  })

  it('covers every emitted quad, including the optional dated ones', async () => {
    const withDates = await annotationsToQuads([record()])
    const withoutDates = await annotationsToQuads([
      record({ createdAt: undefined, updatedAt: undefined }),
    ])

    // Five mandatory quads, plus one per date. If the emitter grows a quad that
    // forgets its graph, the loop above only catches it when this count says
    // the quad is actually reached.
    expect(withoutDates).toHaveLength(5)
    expect(withDates).toHaveLength(7)
    for (const q of withDates) expect(q.graph.termType).toBe('NamedNode')
  })

  it('sends only explicitly public annotations to the shared public graph', async () => {
    const [privateQuad] = await annotationsToQuads([record({ visibility: 'private' })])
    const [publicQuad] = await annotationsToQuads([record({ visibility: 'public' })])

    expect(publicQuad.graph.value).toBe(PUBLIC_GRAPH)
    expect(privateQuad.graph.value).not.toBe(PUBLIC_GRAPH)
  })

  it('fails closed: anything that is not exactly "public" stays out of the public graph', async () => {
    // The values a bug or a hostile input would plausibly produce.
    const notPublic = ['Public', 'PUBLIC', ' public', 'public ', '', null, undefined, 'shared', true, 1]
    for (const visibility of notPublic) {
      const [q] = await annotationsToQuads([record({ visibility })])
      expect(
        q.graph.value,
        `visibility ${JSON.stringify(visibility)} must not reach the public graph`,
      ).not.toBe(PUBLIC_GRAPH)
      expect(safeVisibility(visibility)).not.toBe('public')
    }
  })

  it('separates two users into two graphs, so one cannot read the other by graph', async () => {
    const quads = await annotationsToQuads([
      record({ id: 'a1', userId: 'user-1' }),
      record({ id: 'a2', userId: 'user-2' }),
    ])
    const graphs = new Set(quads.map((q) => q.graph.value))
    expect(graphs.size).toBe(2)
  })

  it('never puts the raw user id in a graph name, a subject or an object', async () => {
    const userId = 'firebase-uid-should-never-appear'
    const quads = await annotationsToQuads([record({ userId })])
    expect(quads.length).toBeGreaterThan(0)
    for (const q of quads) {
      for (const term of [q.subject, q.predicate, q.object, q.graph]) {
        expect(term.value).not.toContain(userId)
      }
    }
  })
})
