// Human-facing tutorial chapters for the public SSTIM Workbench.
// Verified against docs/ADOPTING_SSTIM.md, both released validation clients,
// packages/sstim-mcp/README.md, and examples/tools. Never assert a generated
// IRIs or validate an untested technique by guessing.
export const MANUAL_CHAPTERS = [
  {
    id: 'workbench', title: 'Use the Workbench', short: 'Explore concepts, query the graph and try reference patches.',
    audience: 'Researcher · explorer · practitioner', level: 'No installation',
    intro: 'The Workbench is SSTIM’s non-normative reference application. Explore the ontology and published reference records, write queries, or preview audiovisual patches. It does not prescribe therapeutic treatment or certify efficacy.',
    examples: [
      { title: 'Find the meaning of a stimulation term', goal: 'Look up a canonical IRI, definition, module and neighbouring concepts before using terminology in a study or software model.',
        steps: ['Open Graph Navigator.', 'Search for a term such as “binaural” or “stimulation” using the graph search.', 'Select a node and inspect its full IRI, definition, links and source. Check the source release before citing it.'],
        links: [{ label: 'Open Graph Navigator', href: '/graph/' }] },
      { title: 'Ask an RDF question without installing a SPARQL server', goal: 'List published OWL classes with English labels from the loaded named graphs.',
        steps: ['Open the SPARQL workbench and wait for the static knowledge graph to load.', 'Paste this query and click Run. This is a browser-local query over the loaded RDF store, not a query against a hosted database.'],
        language: 'sparql', code: 'PREFIX owl: <http://www.w3.org/2002/07/owl#>\nPREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\nSELECT DISTINCT ?class ?label WHERE {\n  GRAPH ?graph {\n    ?class a owl:Class .\n    OPTIONAL { ?class rdfs:label ?label . FILTER(LANG(?label) = "en") }\n  }\n}\nORDER BY ?label\nLIMIT 25',
        links: [{label: 'Open SPARQL', href: '/sparql/'}] },
      { title: 'Study a reference preset without conflating evidence and aesthetics', goal: 'Compare public preset records, their intended frequency targets, evidence links and provenance.',
        steps: ['Open Presets and inspect a record rather than treating a name as evidence.', 'Note the technique, target band, source, confidence/evidence fields and what is not asserted.', 'Use the record as a reference. It is not BioSynCare’s private catalog or a clinical recommendation.'],
        links: [{label: 'Browse presets', href: '/presets/'}] },
      { title: 'Author and export a reproducible audiovisual patch', goal: 'Explore time-dependent layers and export a reference patch.',
        steps: ['Open Patch Studio; start with a built-in example or an empty patch.', 'Add or adjust audio and visual tracks, inspect the timeline and preview conservatively.', 'Export the patch and keep the resulting file with your experiment notes. A patch is not automatically a fully validated SSTIM research protocol.'],
        links: [{label: 'Open Patch Studio', href: '/creator/'}] },
      { title: 'Keep observations separate from canonical reference data', goal: 'Use the Logbook for your own notes without rewriting the ontology.',
        steps: ['Open Logbook and create a named personal logbook.', 'Record sessions or reflections and apply tags.', 'Treat logbook data as personal information. Local-browser storage and optional account-scoped behaviour are documented in the Workbench, and none of these notes become published SSTIM ontology assertions.'],
        links: [{label: 'Open Logbook', href: '/logbook/'}] },
    ],
    more: [{label:'Workbench overview',href:'/about/'},{label:'Existing research examples',href:'https://github.com/w3c-cg/sstim/tree/main/examples/tools'}]
  },
  {
    id: 'ontology', title: 'Reuse the ontology', short: 'Choose profiles, publish Turtle and retrieve versioned concepts.',
    audience: 'Data modeller · researcher · integrator', level: 'Beginner to intermediate',
    intro: 'SSTIM supplies shared classes, properties and controlled concepts. You mint your own records under a namespace you control. The released ontology describes vocabulary; it does not validate a scientific effect.',
    examples: [
      {title:'Choose the smallest usable profile',goal:'Avoid downloading an entire ontology when your description only needs a stimulus and its delivery channel.',
        steps:['Use kernel for upper-level process anchors; core for signals/channels/rendering; core-plus when numeric extents are needed; full for techniques, protocols, sessions, exposure and evidence.', 'For a reproducible publication, pin the ontology to a frozen release such as v0.19.0. The unversioned development manifest is not frozen.'],
        links:[{label:'Adoption guide',href:'https://github.com/w3c-cg/sstim/blob/main/docs/ADOPTING_SSTIM.md'}]},
      {title:'Download and inspect an immutable release',goal:'Fetch a release manifest and one of the module files without cloning the repository.',
        steps:['Use the pinned versioned URL. Consult the manifest to find the correct profile closure and SHA-256 checksums.', 'Do not infer module dependencies from filenames or use a mutable development manifest as a fixed citation.'],
        language:'bash', code:'curl -fsSL https://w3id.org/sstim/0.19.0/manifest.json -o sstim-manifest.json\ncurl -fsSL https://w3id.org/sstim/0.19.0/sstim-core.ttl -o sstim-core.ttl',
        links:[{label:'Frozen v0.19.0 manifest',href:'https://w3c-cg.github.io/sstim/ontology/0.19.0/manifest.json'}]},
      {title:'Reuse published terms in your own RDF',goal:'Publish a stimulus record that can be interpreted by other systems using the same stable vocabulary.',
        steps:['Start from the checked Core profile example and replace the example.org namespace with a domain you control.', 'Preserve all sstim: terms exactly and validate before sharing. Never mint new terms under w3id.org/sstim.'],
        language:'bash',code:'curl -fsSL https://raw.githubusercontent.com/w3c-cg/sstim/main/examples/01-stimulus-core.ttl -o my-stimulus.ttl\n# Replace only the example record namespace with your own domain.\n# Then validate using the Python or JavaScript client.',
        links:[{label:'Validated starter examples',href:'https://github.com/w3c-cg/sstim/tree/main/examples'}]},
      {title:'Retrieve concept definitions and mappings as JSON',goal:'Build a local search index, documentation browser or ontology-aware agent using exact published terms.',
        steps:['Fetch the API discovery index, then the release-qualified catalog.', 'Search the catalog client-side by label, IRI or CURIE. Fetch the detail file using the returned relative path; do not derive it from a human-readable label.'],
        language:'javascript',code:"const base = 'https://w3c-cg.github.io/sstim/api/v1/'\nconst discovery = await (await fetch(base + 'index.json')).json()\nconst catalogUrl = new URL(discovery.catalog, base)\nconst catalog = await (await fetch(catalogUrl)).json()\nconst terms = catalog.terms.filter(t => t.label.toLowerCase().includes('stimula'))\nfor (const term of terms.slice(0, 3)) {\n  const detail = await (await fetch(new URL(term.path, catalogUrl))).json()\n  console.log(detail.iri, detail.definitions, detail.relationships)\n}",
        links:[{label:'API contract',href:'https://github.com/w3c-cg/sstim/blob/main/docs/technical/CONCEPT_REFERENCE_API.md'}]},
      {title:'Check that a term really exists',goal:'Avoid invented SSTIM terms and identify the module that defines them.',
        steps:['Search the generated Term Index before concluding a concept is absent.', 'In a repository checkout use locate-iri.py for a direct cross-source check. If the term is missing, propose it through the public contribution flow.'],
        language:'bash',code:'python3 scripts/locate-iri.py sstim:composedOfTrack',
        links:[{label:'Term index',href:'https://github.com/w3c-cg/sstim/blob/main/docs/ontology/TERM_INDEX.md'},{label:'Suggest a term',href:'/contribute/'}]},
    ],
    more:[{label:'Generated OWL reference',href:'/ontology/docs/'},{label:'Controlled SKOS vocabulary',href:'/ontology/docs/vocab/'}]
  },
  {
    id:'python',title:'Python package',short:'Validate RDF, choose profile closures and write session records.',
    audience:'Laboratory · scientific Python · data pipeline',level:'Python 3.10+',
    intro:'The sstim package on PyPI provides release-aware SHACL validation plus checks for profile containment and namespace discipline. The Session builder creates descriptive RDF records; it does not drive or deliver stimulation.',
    examples:[
      {title:'Validate a ready-made Core stimulus',goal:'Check an existing stimulus Turtle file with the complete Python validation pipeline.',
       steps:['Install the package and download the repository’s validated starter file.','Run sstim validate against the frozen Core profile. A successful check is schema conformance, not clinical evidence.'],
       language:'bash',code:'python3 -m pip install "sstim>=0.2,<0.3"\ncurl -fsSL https://raw.githubusercontent.com/w3c-cg/sstim/main/examples/01-stimulus-core.ttl -o stimulus.ttl\nsstim validate stimulus.ttl --profile core --version 0.19.0'},
      {title:'See profile dependencies before modeling',goal:'Understand whether you need kernel, core, core-plus or full.',
       steps:['List the available profiles and the manifest-owned module closure; use this to avoid an accidental dependency on Full.'],
       language:'bash',code:'sstim profiles\nsstim modules --profile full'},
      {title:'Validate many files without resolving the ontology repeatedly',goal:'Apply the exact same frozen release and profile closure across a study dataset.',
       steps:['Resolve the pinned profile once, then validate each record.', 'Review failures; do not treat a valid graph as evidence that the stimulation was effective.'],
       language:'python',code:"from pathlib import Path\nimport sstim\n\nclosure = sstim.resolve_profile('core', version='0.19.0')\nfor path in sorted(Path('records').glob('*.ttl')):\n    report = sstim.validate(str(path), closure=closure)\n    print(path.name, 'PASS' if report else str(report))"},
      {title:'Record a real session from PsychoPy or LSL',goal:'Turn stimulus events and measurements into versioned RDF records with a proper clock provenance.',
       steps:['Use the Session builder in the same process that presents the stimulus, or when converting a stored LSL event stream.', 'Pass actual instrument clock readings and playback-start/stop events; do not fabricate timestamps.', 'Write the session file after the run; the builder validates before writing.'],
       language:'python',code:"import sstim\n# In a real PsychoPy run, core is psychopy.core and the stimulus\n# is actually presented by your existing experiment code.\nstart = core.getTime()\ns = sstim.Session('https://example.org/lab/run-001/',\n    label='10 Hz flicker block', duration=60,\n    master_volume=0.0, timing='monotonic-substitute', clock=start)\nflicker = s.signal(hz=10, shape='square')\ns.channel('Screen disc', modality='visual', medium='visual-light',\n    placement='eyes', signal=flicker, parameter='luminance',\n    mechanism='direct-presentation')\n# Run the actual stimulus here; record its true event timestamp.\ns.event('playback-start', at=core.getTime())\n# After actual playback: s.close(at=core.getTime(), completed=True)\n# Then: s.write('run-001.ttl')",
       links:[{label:'PsychoPy and LSL complete examples',href:'https://github.com/w3c-cg/sstim/tree/main/examples/tools'}],
       caution:'This excerpt illustrates API integration points, not a standalone runnable experiment; PsychoPy and real presentation code must supply core and the actual timing events.'},
      {title:'Run offline after caching a frozen release',goal:'Validate study records in a disconnected lab once a release closure has already been fetched.',
       steps:['Fetch the pinned release at least once online.','On subsequent runs, --offline refuses uncached dependencies rather than silently updating a release.'],
       language:'bash',code:'sstim validate stimulus.ttl --profile core --version 0.19.0 --offline\nsstim cache'},
    ],
    more:[{label:'Python client reference',href:'https://github.com/w3c-cg/sstim/tree/main/packages/sstim'},{label:'PyPI: sstim',href:'https://pypi.org/project/sstim/'}]
  },
  {
    id:'javascript',title:'Node and browser package',short:'Validate stimulus data and build session records in JavaScript.',
    audience:'App developer · frontend · Node.js researcher',level:'Node.js 18+',
    intro:'@sstim/core is the JavaScript validation/session package (distinct from the @sstim/mcp executable). It checks conformance, profile containment and namespace discipline. Its Full-profile SHACL result is PARTIAL because the JavaScript validator does not evaluate sh:sparql constraints.',
    examples:[
      {title:'Validate a Core stimulus from the command line',goal:'Add SSTIM conformance checks to a Node or CI project.',
       steps:['Install the JavaScript client. Download a validated starter file.', 'Use the Core profile when the dataset describes signals and renderings, without Full-only terms.'],
       language:'bash',code:'npm install @sstim/core\ncurl -fsSL https://raw.githubusercontent.com/w3c-cg/sstim/main/examples/01-stimulus-core.ttl -o stimulus.ttl\nnpx sstim validate stimulus.ttl --profile core --version 0.19.0'},
      {title:'Check file conformance in a Node application',goal:'Validate a generated Turtle document before sending it to a collaborator.',
       steps:['Call validate and inspect report.ok.','For Full-profile records, inspect partial and unevaluated; rerun using the Python client for all SHACL-SPARQL checks.'],
       language:'javascript',code:"import { validate } from '@sstim/core'\n\nconst report = await validate('stimulus.ttl', {\n  profile: 'core', version: '0.19.0'\n})\nif (!report.ok) throw new Error(String(report))\nconsole.log('SSTIM Core validation passed')"},
      {title:'Pin one closure across a whole data export',goal:'Avoid drift when generating many RDF files in a Node service.',
       steps:['Resolve the profile once for the frozen release.', 'Reuse the closure for all validation calls instead of resolving release metadata for every file.'],
       language:'javascript',code:"import { resolveProfile, validate } from '@sstim/core'\n\nconst closure = await resolveProfile('core', { version: '0.19.0' })\nfor (const path of files) {\n  const report = await validate(path, { closure })\n  if (!report.ok) console.error(path, String(report))\n}"},
      {title:'Log an auditory-stimulation block with the browser audio clock',goal:'Export an ontology-aligned session record from your application without inventing event timings.',
       steps:['Use the Session builder with a real AudioContext clock and your already-running audio engine.', 'Add the signal and channel description, call event when playback actually starts, then close it after playback and export the Turtle file.'],
       language:'javascript',code:"import { Session } from '@sstim/core/session'\n\nconst session = new Session('https://example.org/lab/run-001/', {\n  label: 'Auditory modulation block', duration: 60,\n  masterVolume: 0.5, timing: 'audio-hardware', clock: ctx.currentTime\n})\nconst tone = session.signal({ hz: 40, shape: 'sine' })\nsession.channel('Headphones', {\n  modality: 'auditory', medium: 'air-conducted-sound',\n  placement: 'ears', signal: tone, parameter: 'amplitude',\n  mechanism: 'amplitude-modulation', carrierHz: 1000\n})\n// When the existing audio engine actually begins playback:\nsession.event('playback-start', { at: ctx.currentTime })\n// After playback finishes, close the record and call session.toTurtle().",
       caution:'Here ctx is your actual AudioContext. The snippet does not create or play an audio stimulus by itself.',
       links:[{label:'Complete jsPsych example',href:'https://github.com/w3c-cg/sstim/tree/main/examples/tools'}]},
      {title:'Know when the JS report is only partial',goal:'Avoid claiming complete Full-profile validation when SPARQL constraints were not evaluated.',
       steps:['For kernel/core/core-plus, JavaScript SHACL checks can run completely.', 'For full, the package explicitly reports PARTIAL and an unevaluated count. Use Python sstim or pySHACL for complete Full validation.'],
       links:[{label:'JavaScript package limitations',href:'https://github.com/w3c-cg/sstim/tree/main/packages/sstim-js'}]},
    ],
    more:[{label:'npm: @sstim/core',href:'https://www.npmjs.com/package/@sstim/core'},{label:'JS client source',href:'https://github.com/w3c-cg/sstim/tree/main/packages/sstim-js'}]
  },
  {
    id:'mcp',title:'MCP for AI assistants',short:'Give Codex, Claude, Copilot, Gemini and Cursor reference access to SSTIM.',
    audience:'AI user · coding agent · researcher',level:'Node.js 20+',
    intro:'@sstim/mcp is a public read-only stdio MCP server, published as io.github.w3c-cg/sstim in the official MCP Registry. It retrieves frozen released concepts, not live clinical findings. Your AI client provides the conversation, code search, comparisons and proposed changes.',
    examples:[
      {title:'Install the MCP server in VS Code/Copilot',goal:'Make SSTIM terms available to your coding assistant with no SSTIM checkout.',
       steps:['Ensure Node.js 20+ and npx are installed.','Put the following JSON in your project’s .vscode/mcp.json, start the server from VS Code’s MCP command palette, then enable its tools in Copilot Agent.'],
       language:'json',code:'{\n  "servers": {\n    "sstim": {\n      "type": "stdio",\n      "command": "npx",\n      "args": ["--yes", "@sstim/mcp@0.2.0"]\n    }\n  }\n}'},
      {title:'Install in Codex, Claude Code or Cursor',goal:'Reuse the same public package from another AI coding client.',
       steps:['For Codex (CLI and VS Code extension), append this to ~/.codex/config.toml.', 'Claude Code: use claude mcp add. Cursor: use .cursor/mcp.json with mcpServers instead of VS Code’s servers.'],
       language:'toml',code:'[mcp_servers.sstim]\ncommand = "npx"\nargs = ["--yes", "@sstim/mcp@0.2.0"]',
       links:[{label:'All client-specific configurations',href:'https://github.com/w3c-cg/sstim/tree/main/packages/sstim-mcp/examples'}]},
      {title:'Ask which vocabulary terms match your software model',goal:'Map parameter fields onto shared ontology identifiers, flagging gaps rather than inventing names.',
       steps:['Ask your agent to inspect an existing application schema or JSON document.', 'Have it search SSTIM and then retrieve exact term records; review its proposed mapping yourself.'],
       prompt:'Inspect my JSON session model and use sstim_search_concepts and sstim_get_concept to propose mappings for signal, carrier frequency, modulation, channel, exposure and session fields. Return exact IRIs, release, mapping rationale and unresolved gaps. Do not invent SSTIM properties.'},
      {title:'Audit a scientific vocabulary in a paper',goal:'Replace ambiguous language with defined terms without misrepresenting mechanism or evidence.',
       steps:['Ask the agent to search for each key term.','Have it quote or paraphrase the definitions with release and provenance; verify whether distinctions like stimulus rate vs neural band are represented.'],
       prompt:'Find published SSTIM terms related to binaural stimulation, isochronous modulation and oscillatory bands. For each, give the canonical IRI, definition, relevant relationships and the source release. Distinguish asserted ontology facts from your interpretation.'},
      {title:'Compare two frozen releases',goal:'Detect whether term descriptions or mappings changed, useful for migrations and manuscript reproducibility.',
       steps:['Use an exact IRI/CURIE and query the term in release 0.18.0 and 0.19.0.', 'Compare the returned definitions and relationships. An absent term is a meaningful result, not an invitation to invent one.'],
       prompt:'Use sstim_get_concept to retrieve the same exact concept IRI from SSTIM v0.18.0 and v0.19.0. Compare labels, definitions, relationships, deprecation status and provenance. Report only verifiable differences.'},
      {title:'Crosswalk external research vocabularies',goal:'Inspect SKOS mappings and their strength when relating SSTIM to adjacent ontologies.',
       steps:['Search for the relevant SSTIM concept.','Inspect exactMatch, closeMatch, broadMatch and other predicate types rather than treating all mappings as identical.'],
       prompt:'Retrieve SSTIM terms related to sensory stimulation and list their external mappings with exact target IRIs, predicate types, and source provenance. Do not interpret a SKOS mapping as clinical validation.'},
      {title:'Create a reviewer-controlled contribution',goal:'Report a missing definition or propose an improvement without automatically modifying the ontology.',
       steps:['Have the agent identify the exact term or confirm the gap.', 'Call sstim_prepare_feedback to generate a reviewable Contribution Bridge link. The user chooses whether to open and submit an issue.'],
       prompt:'Find the SSTIM term most closely related to my proposed concept. Explain whether it is already covered. If not, prepare a Contribution Bridge link and a proposed definition for my review. Do not submit the issue or alter canonical files.'},
      {title:'Use SSTIM to guide a small data-pipeline refactor',goal:'Make a coding assistant check interoperability assumptions against the current reference before changing code.',
       steps:['Ask the agent to inspect the repository schema and tests.', 'Have it identify SSTIM term matches and gaps with source provenance, then propose a minimal version-pinned migration plan.'],
       prompt:'Inspect the stimulus-related fields in this repository. Search SSTIM MCP for canonical equivalents, propose a minimal version-pinned mapping plan, and add tests only for relationships supported by the published ontology. Ask before editing code.'},
    ],
    more:[{label:'MCP setup reference',href:'https://github.com/w3c-cg/sstim/tree/main/packages/sstim-mcp'},{label:'Official Registry publication',href:'https://github.com/w3c-cg/sstim/actions/runs/38037758861'},{label:'npm package',href:'https://www.npmjs.com/package/@sstim/mcp'}]
  },
  {
    id:'repository',title:'Work with the repository',short:'Run the Workbench, validate examples and contribute reproducibly.',
    audience:'Contributor · maintainer · developer',level:'Git + Node + Python',
    intro:'The source repository hosts the formal ontology, developer documentation, reference Workbench, validation clients and MCP adapter. Not all repository data are canonical release artifacts; ontology edits require explicit review and release procedures.',
    examples:[
      {title:'Run SSTIM Workbench locally',goal:'Study its RDF graph and Patch Studio while iterating on reference software.',
       steps:['Clone the canonical source and install Node dependencies.','Start the dev server and use the local URL printed by Vite. Nothing you change locally alters the official ontology.'],
       language:'bash',code:'git clone https://github.com/w3c-cg/sstim.git\ncd sstim\nnpm ci\nnpm run dev'},
      {title:'Run the application test and quality checks',goal:'Keep UI changes reproducible across the reference Web application.',
       steps:['Run Svelte checks and Vitest; run the static build before publication.', 'For ontology changes use the repository’s dedicated validation targets and review the release notes.'],
       language:'bash',code:'npm run check\nnpm test\nnpm run build\n# For authorized changes that touch canonical ontology:\nmake validate'},
      {title:'Inspect the published vocabulary without guessing',goal:'Find where a term is defined, what belongs to its module, and whether an IRI is already used.',
       steps:['Use the generated term index, then the locate-iri.py helper for the precise identifier.', 'Read the appropriate documentation and module manifest before proposing a new term.'],
       language:'bash',code:'python3 scripts/locate-iri.py sstim:composedOfTrack\n# Also consult docs/ontology/TERM_INDEX.md'},
      {title:'Check real interoperability with a release-pinned example',goal:'Confirm that a new example fits the profile it claims without silently using undeclared terms.',
       steps:['Start from examples/01-stimulus-core.ttl and make your own copy.', 'Run the example checker and the Python client validator. The example checker also includes negative fixtures that must fail for the right reasons.'],
       language:'bash',code:'make examples-check\npython3 -m pip install sstim\nsstim validate examples/01-stimulus-core.ttl --profile core --version 0.19.0'},
      {title:'Contribute without overwriting the canonical vocabulary',goal:'Propose edits to definitions, external alignments or new terms through human review.',
       steps:['Read CONTRIBUTING.md and CLAUDE.md before changing code or ontology.', 'Use the Contribution Bridge for terminology proposals; submit source changes through the established review process.', 'Keep original historical BSC Lab IRIs and citations intact rather than mechanically renaming them.'],
       links:[{label:'Contribution Bridge',href:'/contribute/'},{label:'CONTRIBUTING.md',href:'https://github.com/w3c-cg/sstim/blob/main/CONTRIBUTING.md'}]},
      {title:'Understand dual remote publication (maintainers only)',goal:'Preserve identical commit histories between the legacy origin and canonical W3C repository.',
       steps:['Public contributors normally work through issues and PRs.', 'Maintainers with both remotes configured use make push after review; do not push independently generated commits to both remotes.', 'Do not edit static/ontology files merely to update a manual, package README or developer example.'],
       language:'bash',code:'# Authorized maintainers only, from a fully validated checkout:\nmake push'},
    ],
    more:[{label:'Repository source',href:'https://github.com/w3c-cg/sstim'},{label:'Contribution guidance',href:'https://github.com/w3c-cg/sstim/blob/main/CONTRIBUTING.md'},{label:'Adopting SSTIM',href:'https://github.com/w3c-cg/sstim/blob/main/docs/ADOPTING_SSTIM.md'}]
  }
]

export const MANUAL_IDS = MANUAL_CHAPTERS.map(chapter => chapter.id)
export function getManualChapter(id) {
  return MANUAL_CHAPTERS.find(chapter => chapter.id === id)
}
