// The public stakeholder directory of the sensory-stimulation ecosystem
// (ADR 0062), rendered at /ecosystem/directory/.
//
// A listing, not a record. An entry says that a company, laboratory, person,
// society, standard or project is relevant to the field, from one public
// source, and nothing else: not that anyone was contacted, agreed, endorsed
// SSTIM, or conforms to it. Only public professional facts belong here; no
// contact details. Every URL was fetched and its page checked on
// DIRECTORY_REVIEWED.
//
// The qualified, retractable record of an agent lives in the external live
// store (ADR 0031). `agent` names the path an entry would have there, and the
// page asks the live graph whether it does; this file never claims it.

export const DIRECTORY_REVIEWED = '2026-10-08'

export const DIRECTORY_KINDS = [
  { id: 'company', label: 'Company' },
  { id: 'lab', label: 'Laboratory or research centre' },
  { id: 'person', label: 'Person' },
  { id: 'organization', label: 'Society or nonprofit' },
  { id: 'standard', label: 'Standard' },
  { id: 'project', label: 'Project or open tool' },
]

// Sensory modalities first; the rest name the adjacent fields an entry belongs
// to when the domain-review status is `related`.
export const DIRECTORY_MODALITIES = [
  { id: 'auditory', label: 'Auditory' },
  { id: 'visual', label: 'Visual' },
  { id: 'tactile', label: 'Tactile' },
  { id: 'olfactory', label: 'Olfactory' },
  { id: 'vestibular', label: 'Vestibular' },
  { id: 'multisensory', label: 'Multisensory' },
  { id: 'electrical', label: 'Electrical stimulation' },
  { id: 'magnetic', label: 'Magnetic stimulation' },
  { id: 'light', label: 'Photobiomodulation' },
  { id: 'feedback', label: 'Neurofeedback and biofeedback' },
]

export const DIRECTORY_ERAS = [
  { id: 'active', label: 'Active' },
  { id: 'past', label: 'Past' },
  { id: 'planned', label: 'Planned' },
]

export const STAKEHOLDERS = [
  {
    id: 'cognito-therapeutics',
    name: 'Cognito Therapeutics',
    kind: 'company',
    country: 'United States',
    modalities: ['visual', 'auditory'],
    review: 'candidate',
    era: 'active',
    url: 'https://www.cognitotx.com',
    agent: 'organization/cognito-therapeutics',
    summary: 'Develops a headset that delivers 40 Hz light and sound stimulation (gamma sensory stimulation), in clinical trials for Alzheimer’s disease.',
  },
  {
    id: 'optoceutics',
    name: 'OptoCeutics',
    kind: 'company',
    country: 'Denmark',
    modalities: ['visual'],
    review: 'candidate',
    era: 'active',
    url: 'https://www.optoceutics.com',
    agent: 'organization/optoceutics',
    summary: 'Develops 40 Hz light stimulation designed to look steady to the viewer (invisible spectral flicker), studied in dementia research.',
  },
  {
    id: 'neosensory',
    name: 'Neosensory',
    kind: 'company',
    country: 'United States',
    modalities: ['tactile', 'auditory'],
    review: 'candidate',
    era: 'past',
    url: 'https://web.archive.org/web/20241228134827/https://neosensory.com/',
    summary: 'Made wrist-worn devices that translated sound into vibration, including a program pairing tones with touch for tinnitus; the company has since closed and sold its technology.',
  },
  {
    id: 'elemind',
    name: 'Elemind Technologies',
    kind: 'company',
    country: 'United States',
    modalities: ['auditory'],
    review: 'candidate',
    era: 'active',
    url: 'https://elemindtech.com',
    agent: 'organization/elemind-technologies',
    summary: 'Makes an EEG headband that plays sound timed to the wearer’s brain rhythms (closed-loop acoustic stimulation) around sleep onset.',
  },
  {
    id: 'neuromod-devices',
    name: 'Neuromod Devices (Lenire)',
    kind: 'company',
    country: 'Ireland',
    modalities: ['auditory', 'tactile'],
    review: 'candidate',
    era: 'active',
    url: 'https://www.lenire.com',
    agent: 'organization/neuromod-devices',
    summary: 'Makes Lenire, a bimodal device that pairs sound through headphones with mild electrical stimulation of the tongue, authorised for tinnitus.',
  },
  {
    id: 'mind-alive',
    name: 'Mind Alive',
    kind: 'company',
    country: 'Canada',
    modalities: ['visual', 'auditory'],
    review: 'candidate',
    era: 'active',
    url: 'https://www.mindalive.com',
    summary: 'Makes the DAVID line of audio-visual entrainment devices, light glasses paired with pulsed sound.',
  },
  {
    id: 'apollo-neuroscience',
    name: 'Apollo Neuroscience',
    kind: 'company',
    country: 'United States',
    modalities: ['tactile'],
    review: 'candidate',
    era: 'active',
    url: 'https://apolloneuro.com',
    agent: 'organization/apollo-neuroscience',
    summary: 'Makes a wearable that delivers low-frequency vibration patterns intended to support relaxation and focus.',
  },
  {
    id: 'brain-fm',
    name: 'Brain.fm',
    kind: 'company',
    country: 'United States',
    modalities: ['auditory'],
    review: 'candidate',
    era: 'active',
    url: 'https://www.brain.fm',
    summary: 'Produces functional music with engineered amplitude modulation for focus, relaxation and sleep.',
  },
  {
    id: 'endel',
    name: 'Endel',
    kind: 'company',
    country: 'Germany',
    modalities: ['auditory'],
    review: 'candidate',
    era: 'active',
    url: 'https://endel.io',
    summary: 'Generates adaptive, personalized soundscapes for focus, relaxation and sleep.',
  },
  {
    id: 'lucia-light',
    name: 'Lucia Light',
    kind: 'company',
    country: 'Austria',
    modalities: ['visual'],
    review: 'candidate',
    era: 'active',
    url: 'https://www.lucialight.com',
    summary: 'Makes the Lucia hypnagogic light, which combines flickering and constant light viewed with the eyes closed.',
  },
  {
    id: 'lumenate',
    name: 'Lumenate',
    kind: 'company',
    country: 'United Kingdom',
    modalities: ['visual', 'auditory'],
    review: 'candidate',
    era: 'active',
    url: 'https://lumenate.co',
    summary: 'An app that flickers a phone’s flashlight, viewed with the eyes closed, alongside guided audio.',
  },
  {
    id: 'braintap',
    name: 'BrainTap',
    kind: 'company',
    country: 'United States',
    modalities: ['visual', 'auditory'],
    review: 'candidate',
    era: 'active',
    url: 'https://braintap.com',
    summary: 'Makes a headset and app that combine light patterns with audio programs that use binaural beats.',
  },
  {
    id: 'neurovizr',
    name: 'NeuroVIZR',
    kind: 'company',
    country: 'United States',
    modalities: ['visual', 'auditory'],
    review: 'candidate',
    era: 'active',
    url: 'https://neurovizr.com',
    summary: 'Makes a stroboscopic light device paired with audio programs, used with the eyes closed.',
  },
  {
    id: 'unyte-health',
    name: 'Unyte Health (Integrated Listening Systems)',
    kind: 'company',
    country: 'United States',
    modalities: ['auditory'],
    review: 'candidate',
    era: 'active',
    url: 'https://integratedlistening.com',
    summary: 'Provides the Safe and Sound Protocol and other filtered-music listening programs delivered through practitioners.',
  },
  {
    id: 'tomatis',
    name: 'Tomatis Développement',
    kind: 'company',
    country: 'Luxembourg',
    modalities: ['auditory'],
    review: 'candidate',
    era: 'active',
    url: 'https://www.tomatis.com',
    summary: 'Offers the Tomatis method, listening programs built on electronically processed music and bone conduction.',
  },
  {
    id: 'sensate',
    name: 'Sensate',
    kind: 'company',
    modalities: ['tactile', 'auditory'],
    review: 'candidate',
    era: 'active',
    url: 'https://www.getsensate.com',
    summary: 'Makes a chest-worn device that delivers infrasonic vibration paired with soundscapes.',
  },
  {
    id: 'touchpoints',
    name: 'TouchPoints',
    kind: 'company',
    country: 'United States',
    modalities: ['tactile'],
    review: 'candidate',
    era: 'active',
    url: 'https://thetouchpointsolution.com',
    summary: 'Makes a pair of wearables that deliver bilateral alternating vibration.',
  },
  {
    id: 'woojer',
    name: 'Woojer',
    kind: 'company',
    country: 'Israel',
    modalities: ['tactile', 'auditory'],
    review: 'candidate',
    era: 'active',
    url: 'https://www.woojer.com',
    summary: 'Makes wearable haptic vests and straps that render audio as vibration.',
  },
  {
    id: 'subpac',
    name: 'SUBPAC',
    kind: 'company',
    country: 'Canada',
    modalities: ['tactile', 'auditory'],
    review: 'candidate',
    era: 'active',
    url: 'https://subpac.com',
    summary: 'Makes wearable tactile transducers that render low-frequency sound as vibration on the body.',
  },
  {
    id: 'bhaptics',
    name: 'bHaptics',
    kind: 'company',
    country: 'South Korea',
    modalities: ['tactile'],
    review: 'candidate',
    era: 'active',
    url: 'https://www.bhaptics.com',
    summary: 'Makes haptic vests, sleeves and gloves for virtual reality.',
  },
  {
    id: 'ultraleap',
    name: 'Ultraleap',
    kind: 'company',
    country: 'United Kingdom',
    modalities: ['tactile'],
    review: 'candidate',
    era: 'active',
    url: 'https://www.ultraleap.com',
    summary: 'Develops hand tracking and mid-air haptics, touch sensations produced by focused ultrasound.',
  },
  {
    id: 'ovr-technology',
    name: 'OVR Technology',
    kind: 'company',
    country: 'United States',
    modalities: ['olfactory'],
    review: 'candidate',
    era: 'active',
    url: 'https://ovrtechnology.com',
    summary: 'Develops scent delivery hardware and software for virtual reality.',
  },
  {
    id: 'luminette',
    name: 'Luminette (Lucimed)',
    kind: 'company',
    country: 'Belgium',
    modalities: ['visual'],
    review: 'candidate',
    era: 'active',
    url: 'https://www.myluminette.com',
    summary: 'Makes light-therapy glasses that direct blue-enriched light toward the eyes.',
  },
  {
    id: 'sana-health',
    name: 'Sana Health',
    kind: 'company',
    country: 'United States',
    modalities: ['visual', 'auditory'],
    review: 'candidate',
    era: 'active',
    url: 'https://sana.io',
    summary: 'Develops a mask that delivers pulsed light and sound, studied for pain and sleep.',
  },
  {
    id: 'moonbird',
    name: 'Moonbird',
    kind: 'company',
    country: 'Belgium',
    modalities: ['tactile'],
    review: 'candidate',
    era: 'active',
    url: 'https://www.moonbird.life',
    summary: 'Makes a handheld device that expands and contracts to pace the user’s breathing by touch.',
  },
  {
    id: 'somnox',
    name: 'Somnox',
    kind: 'company',
    country: 'Netherlands',
    modalities: ['tactile'],
    review: 'candidate',
    era: 'active',
    url: 'https://somnox.com',
    summary: 'Makes a pillow-like device that simulates slow breathing movement to pace the user’s breathing.',
  },
  {
    id: 'otolith-labs',
    name: 'Otolith Labs',
    kind: 'company',
    country: 'United States',
    modalities: ['tactile', 'vestibular'],
    review: 'candidate',
    era: 'active',
    url: 'https://www.otolithlabs.com',
    summary: 'Develops a head-worn vibration device studied for vertigo.',
  },
  {
    id: 'mynoise',
    name: 'myNoise',
    kind: 'project',
    country: 'Belgium',
    modalities: ['auditory'],
    review: 'candidate',
    era: 'active',
    url: 'https://mynoise.net',
    summary: 'Website of calibrated noise and soundscape generators, created by Stéphane Pigeon.',
  },
  {
    id: 'monroe-institute',
    name: 'The Monroe Institute',
    kind: 'organization',
    country: 'United States',
    modalities: ['auditory'],
    review: 'candidate',
    era: 'active',
    url: 'https://www.monroeinstitute.org',
    summary: 'Nonprofit that developed Hemi-Sync binaural-beat audio and runs residential programs.',
  },
  {
    id: 'flow-neuroscience',
    name: 'Flow Neuroscience',
    kind: 'company',
    country: 'Sweden',
    modalities: ['electrical'],
    review: 'related',
    era: 'active',
    url: 'https://www.flowneuroscience.com',
    summary: 'Makes a transcranial direct current stimulation (tDCS) headset for depression.',
  },
  {
    id: 'neuroelectrics',
    name: 'Neuroelectrics',
    kind: 'company',
    country: 'Spain',
    modalities: ['electrical'],
    review: 'related',
    era: 'active',
    url: 'https://www.neuroelectrics.com',
    summary: 'Makes transcranial electrical stimulation and EEG systems for research and clinical use.',
  },
  {
    id: 'soterix-medical',
    name: 'Soterix Medical',
    kind: 'company',
    country: 'United States',
    modalities: ['electrical'],
    review: 'related',
    era: 'active',
    url: 'https://soterixmedical.com',
    summary: 'Makes transcranial electrical stimulation devices, including high-definition tDCS.',
  },
  {
    id: 'magstim',
    name: 'Magstim',
    kind: 'company',
    country: 'United Kingdom',
    modalities: ['magnetic'],
    review: 'related',
    era: 'active',
    url: 'https://www.magstim.com',
    summary: 'Makes transcranial magnetic stimulation (TMS) systems.',
  },
  {
    id: 'brainsway',
    name: 'BrainsWay',
    kind: 'company',
    country: 'Israel',
    modalities: ['magnetic'],
    review: 'related',
    era: 'active',
    url: 'https://www.brainsway.com',
    summary: 'Makes deep transcranial magnetic stimulation systems.',
  },
  {
    id: 'neuronetics',
    name: 'Neuronetics (NeuroStar)',
    kind: 'company',
    country: 'United States',
    modalities: ['magnetic'],
    review: 'related',
    era: 'active',
    url: 'https://neurostar.com',
    summary: 'Makes the NeuroStar transcranial magnetic stimulation system.',
  },
  {
    id: 'fisher-wallace',
    name: 'Fisher Wallace Laboratories',
    kind: 'company',
    country: 'United States',
    modalities: ['electrical'],
    review: 'related',
    era: 'active',
    url: 'https://www.fisherwallace.com',
    summary: 'Makes a cranial electrotherapy stimulation device.',
  },
  {
    id: 'alpha-stim',
    name: 'Alpha-Stim (Electromedical Products International)',
    kind: 'company',
    country: 'United States',
    modalities: ['electrical'],
    review: 'related',
    era: 'active',
    url: 'https://www.alpha-stim.com',
    summary: 'Makes cranial electrotherapy stimulation and microcurrent devices.',
  },
  {
    id: 'somnee',
    name: 'Somnee',
    kind: 'company',
    country: 'United States',
    modalities: ['electrical'],
    review: 'related',
    era: 'active',
    url: 'https://somneesleep.com',
    summary: 'Makes a headband that delivers transcranial electrical stimulation for sleep.',
  },
  {
    id: 'neurovalens',
    name: 'Neurovalens',
    kind: 'company',
    country: 'United Kingdom',
    modalities: ['electrical', 'vestibular'],
    review: 'related',
    era: 'active',
    url: 'https://www.neurovalens.com',
    summary: 'Develops head-worn devices that stimulate the vestibular nerve electrically.',
  },
  {
    id: 'vielight',
    name: 'Vielight',
    kind: 'company',
    country: 'Canada',
    modalities: ['light'],
    review: 'related',
    era: 'active',
    url: 'https://www.vielight.com',
    summary: 'Makes transcranial and intranasal near-infrared photobiomodulation devices.',
  },
  {
    id: 'interaxon-muse',
    name: 'Interaxon (Muse)',
    kind: 'company',
    country: 'Canada',
    modalities: ['feedback'],
    review: 'related',
    era: 'active',
    url: 'https://choosemuse.com',
    summary: 'Makes the Muse EEG headband, which turns brain activity into sound feedback during meditation.',
  },
  {
    id: 'mendi',
    name: 'Mendi',
    kind: 'company',
    country: 'Sweden',
    modalities: ['feedback'],
    review: 'related',
    era: 'active',
    url: 'https://www.mendi.io',
    summary: 'Makes a headband for fNIRS neurofeedback training.',
  },
  {
    id: 'openbci',
    name: 'OpenBCI',
    kind: 'company',
    country: 'United States',
    modalities: ['feedback'],
    review: 'related',
    era: 'active',
    url: 'https://openbci.com',
    summary: 'Makes open-source biosensing hardware, used in closed-loop stimulation and neurofeedback research.',
  },
  {
    id: 'tsai-laboratory',
    name: 'Tsai Laboratory, Picower Institute, MIT',
    kind: 'lab',
    country: 'United States',
    modalities: ['visual', 'auditory'],
    review: 'candidate',
    era: 'active',
    url: 'https://picower.mit.edu/li-huei-tsai',
    agent: 'organization/tsai-laboratory-mit',
    summary: 'Li-Huei Tsai’s laboratory, which introduced gamma entrainment using sensory stimuli (GENUS), 40 Hz light and sound, in models of Alzheimer’s disease.',
  },
  {
    id: 'singer-lab',
    name: 'Singer Lab, Georgia Tech and Emory University',
    kind: 'lab',
    country: 'United States',
    modalities: ['visual', 'auditory'],
    review: 'candidate',
    era: 'active',
    url: 'https://singer.gatech.edu',
    agent: 'organization/singer-lab',
    summary: 'Annabelle Singer’s laboratory, which studies how flicker and other sensory stimulation drive neural activity and brain immune responses.',
  },
  {
    id: 'mahrc',
    name: 'Music and Health Science Research Collaboratory, University of Toronto',
    kind: 'lab',
    country: 'Canada',
    modalities: ['auditory'],
    review: 'candidate',
    era: 'active',
    url: 'https://mahrc.music.utoronto.ca',
    agent: 'organization/music-and-health-science-research-collaboratory',
    summary: 'Michael Thaut’s research centre on music and the brain, which developed Neurologic Music Therapy and rhythmic auditory stimulation for movement rehabilitation.',
  },
  {
    id: 'brams',
    name: 'International Laboratory for Brain, Music and Sound Research (BRAMS)',
    kind: 'lab',
    country: 'Canada',
    modalities: ['auditory'],
    review: 'candidate',
    era: 'active',
    url: 'https://www.brams.org',
    summary: 'Montreal research centre on music, auditory cognition and rhythm, including rhythm-based interventions.',
  },
  {
    id: 'music-in-the-brain',
    name: 'Center for Music in the Brain, Aarhus University',
    kind: 'lab',
    country: 'Denmark',
    modalities: ['auditory'],
    review: 'candidate',
    era: 'active',
    url: 'https://musicinthebrain.au.dk',
    summary: 'Research centre on how music affects the brain, including music-based interventions.',
  },
  {
    id: 'brainvolts',
    name: 'Brainvolts, Northwestern University',
    kind: 'lab',
    country: 'United States',
    modalities: ['auditory'],
    review: 'candidate',
    era: 'active',
    url: 'https://brainvolts.northwestern.edu',
    summary: 'Nina Kraus’s auditory neuroscience laboratory, studying how sound and music experience shape the brain.',
  },
  {
    id: 'paller-lab',
    name: 'Paller Lab, Northwestern University',
    kind: 'lab',
    country: 'United States',
    modalities: ['auditory'],
    review: 'candidate',
    era: 'active',
    url: 'https://sites.northwestern.edu/pallerlab/',
    summary: 'Ken Paller’s laboratory, which studies memory reactivation by sound cues during sleep.',
  },
  {
    id: 'neuroscape',
    name: 'Neuroscape, University of California San Francisco',
    kind: 'lab',
    country: 'United States',
    modalities: ['visual', 'auditory'],
    review: 'candidate',
    era: 'active',
    url: 'https://neuroscape.ucsf.edu',
    summary: 'Translational neuroscience centre that develops and tests closed-loop digital interventions, such as video games, for cognition.',
  },
  {
    id: 'sussex-consciousness',
    name: 'Sussex Centre for Consciousness Science',
    kind: 'lab',
    country: 'United Kingdom',
    modalities: ['visual'],
    review: 'candidate',
    era: 'active',
    url: 'https://www.sussex.ac.uk/research/centres/sussex-centre-for-consciousness-science',
    summary: 'Research centre on consciousness, including research on flicker-induced visual experiences with the Dreamachine project.',
  },
  {
    id: 'cerco',
    name: 'Brain and Cognition Research Centre (CerCo), Toulouse',
    kind: 'lab',
    country: 'France',
    modalities: ['visual'],
    review: 'candidate',
    era: 'active',
    url: 'https://cerco.cnrs.fr',
    summary: 'CNRS research centre whose work includes rhythmic visual stimulation and the rhythms of perception.',
  },
  {
    id: 'hi-mpi',
    name: 'Haptic Intelligence Department, Max Planck Institute for Intelligent Systems',
    kind: 'lab',
    country: 'Germany',
    modalities: ['tactile'],
    review: 'candidate',
    era: 'active',
    url: 'https://hi.is.mpg.de',
    summary: 'Research department on haptic interfaces and touch, led by Katherine J. Kuchenbecker.',
  },
  {
    id: 'charm-lab',
    name: 'CHARM Lab, Stanford University',
    kind: 'lab',
    country: 'United States',
    modalities: ['tactile'],
    review: 'candidate',
    era: 'active',
    url: 'https://charm.stanford.edu',
    summary: 'Allison Okamura’s laboratory on haptics, wearable touch feedback and medical robotics.',
  },
  {
    id: 'kresge-hearing',
    name: 'Kresge Hearing Research Institute, University of Michigan',
    kind: 'lab',
    country: 'United States',
    modalities: ['auditory', 'tactile'],
    review: 'candidate',
    era: 'active',
    url: 'https://medicine.umich.edu/dept/khri',
    summary: 'Hearing research institute whose work includes bimodal sound and touch stimulation for tinnitus (Susan Shore’s laboratory).',
  },
  {
    id: 'iit-uvip',
    name: 'Unit for Visually Impaired People, Italian Institute of Technology',
    kind: 'lab',
    country: 'Italy',
    modalities: ['auditory', 'tactile'],
    review: 'candidate',
    era: 'active',
    url: 'https://www.iit.it/web/unit-for-visually-impaired-people',
    summary: 'Monica Gori’s research unit, developing audio and tactile devices for multisensory rehabilitation of children with visual impairment.',
  },
  {
    id: 'smell-taste-dresden',
    name: 'Interdisciplinary Centre for Smell and Taste, University Hospital Dresden',
    kind: 'lab',
    country: 'Germany',
    modalities: ['olfactory'],
    review: 'candidate',
    era: 'active',
    url: 'https://www.uniklinikum-dresden.de/de/das-klinikum/kliniken-polikliniken-institute/hno/forschung/interdisziplinaeres-zentrum-fuer-riechen-und-schmecken',
    summary: 'Clinical and research centre for smell and taste disorders, known for research on olfactory training.',
  },
  {
    id: 'heinrich-wilhelm-dove',
    name: 'Heinrich Wilhelm Dove',
    kind: 'person',
    country: 'Germany',
    modalities: ['auditory'],
    review: 'candidate',
    era: 'past',
    url: 'https://en.wikipedia.org/wiki/Heinrich_Wilhelm_Dove',
    summary: 'Physicist who described binaural beats in 1839.',
  },
  {
    id: 'gerald-oster',
    name: 'Gerald Oster',
    kind: 'person',
    country: 'United States',
    modalities: ['auditory'],
    review: 'candidate',
    era: 'past',
    url: 'https://doi.org/10.1038/scientificamerican1073-94',
    summary: 'Biophysicist whose 1973 article "Auditory beats in the brain" in Scientific American brought binaural beats to wide attention.',
  },
  {
    id: 'edgar-adrian',
    name: 'Edgar Adrian',
    kind: 'person',
    country: 'United Kingdom',
    modalities: ['visual'],
    review: 'candidate',
    era: 'past',
    url: 'https://en.wikipedia.org/wiki/Edgar_Adrian,_1st_Baron_Adrian',
    summary: 'Physiologist who, with B. H. C. Matthews, reported in 1934 that the EEG follows flickering light (photic driving).',
  },
  {
    id: 'william-grey-walter',
    name: 'William Grey Walter',
    kind: 'person',
    country: 'United Kingdom',
    modalities: ['visual'],
    review: 'candidate',
    era: 'past',
    url: 'https://en.wikipedia.org/wiki/William_Grey_Walter',
    summary: 'Neurophysiologist whose work on flicker and photic driving in the 1940s and 1950s shaped research on rhythmic visual stimulation.',
  },
  {
    id: 'brion-gysin',
    name: 'Brion Gysin',
    kind: 'person',
    country: 'United Kingdom',
    modalities: ['visual'],
    review: 'candidate',
    era: 'past',
    url: 'https://en.wikipedia.org/wiki/Brion_Gysin',
    summary: 'Artist who built the Dreamachine with Ian Sommerville around 1960, a flicker device viewed with the eyes closed.',
  },
  {
    id: 'paul-bach-y-rita',
    name: 'Paul Bach-y-Rita',
    kind: 'person',
    country: 'United States',
    modalities: ['tactile', 'visual'],
    review: 'candidate',
    era: 'past',
    url: 'https://en.wikipedia.org/wiki/Paul_Bach-y-Rita',
    summary: 'Neuroscientist who pioneered sensory substitution, including tactile-visual substitution systems.',
  },
  {
    id: 'david-eagleman',
    name: 'David Eagleman',
    kind: 'person',
    country: 'United States',
    modalities: ['tactile', 'auditory'],
    review: 'candidate',
    era: 'active',
    url: 'https://eagleman.com',
    summary: 'Neuroscientist working on sensory substitution and augmentation; co-founder of Neosensory.',
  },
  {
    id: 'peter-tass',
    name: 'Peter Tass',
    kind: 'person',
    country: 'United States',
    modalities: ['auditory', 'tactile'],
    review: 'candidate',
    era: 'active',
    url: 'https://profiles.stanford.edu/peter-tass',
    summary: 'Neuroscientist who developed coordinated reset stimulation, including acoustic and vibrotactile variants.',
  },
  {
    id: 'jan-born',
    name: 'Jan Born',
    kind: 'person',
    country: 'Germany',
    modalities: ['auditory'],
    review: 'candidate',
    era: 'active',
    url: 'https://en.wikipedia.org/wiki/Jan_Born',
    summary: 'Neuroscientist whose group showed in 2013 that sound pulses timed to sleep slow oscillations enhance them.',
  },
  {
    id: 'gregor-thut',
    name: 'Gregor Thut',
    kind: 'person',
    country: 'United Kingdom',
    modalities: ['visual', 'auditory'],
    review: 'candidate',
    era: 'active',
    url: 'https://www.gla.ac.uk/schools/psychologyneuroscience/staff/gregorthut/',
    summary: 'Neuroscientist studying how rhythmic sensory and transcranial stimulation entrain brain rhythms.',
  },
  {
    id: 'fiona-macpherson',
    name: 'Fiona Macpherson',
    kind: 'person',
    country: 'United Kingdom',
    modalities: ['visual'],
    review: 'candidate',
    era: 'active',
    url: 'https://en.wikipedia.org/wiki/Fiona_Macpherson',
    summary: 'Philosopher of perception who led research on the Dreamachine and the Perception Census.',
  },
  {
    id: 'amta',
    name: 'American Music Therapy Association',
    kind: 'organization',
    country: 'United States',
    modalities: ['auditory'],
    review: 'candidate',
    era: 'active',
    url: 'https://www.musictherapy.org',
    summary: 'Professional association for music therapy in the United States.',
  },
  {
    id: 'wfmt',
    name: 'World Federation of Music Therapy',
    kind: 'organization',
    country: 'International',
    modalities: ['auditory'],
    review: 'candidate',
    era: 'active',
    url: 'https://www.wfmt.info',
    summary: 'International organisation of music therapy associations and practitioners.',
  },
  {
    id: 'sltbr',
    name: 'Society for Light Treatment and Biological Rhythms',
    kind: 'organization',
    country: 'International',
    modalities: ['visual'],
    review: 'candidate',
    era: 'active',
    url: 'https://sltbr.org',
    summary: 'Scientific society for research on light treatment and biological rhythms.',
  },
  {
    id: 'achems',
    name: 'Association for Chemoreception Sciences',
    kind: 'organization',
    country: 'United States',
    modalities: ['olfactory'],
    review: 'candidate',
    era: 'active',
    url: 'https://www.achems.org',
    summary: 'Scientific society for research on smell, taste and chemical senses.',
  },
  {
    id: 'isnr',
    name: 'International Society for Neuroregulation and Research',
    kind: 'organization',
    country: 'International',
    modalities: ['feedback'],
    review: 'related',
    era: 'active',
    url: 'https://isnr.org',
    summary: 'Professional society for neurofeedback and neuroregulation research and practice.',
  },
  {
    id: 'aapb',
    name: 'Association for Applied Psychophysiology and Biofeedback',
    kind: 'organization',
    country: 'United States',
    modalities: ['feedback'],
    review: 'related',
    era: 'active',
    url: 'https://www.aapb.org',
    summary: 'Professional association for biofeedback and applied psychophysiology.',
  },
  {
    id: 'ins',
    name: 'International Neuromodulation Society',
    kind: 'organization',
    country: 'International',
    modalities: ['electrical', 'magnetic'],
    review: 'related',
    era: 'active',
    url: 'https://www.neuromodulation.com',
    summary: 'Scientific society for neuromodulation therapies.',
  },
  {
    id: 'hed',
    name: 'HED Working Group',
    kind: 'standard',
    country: 'International',
    modalities: ['multisensory'],
    review: 'candidate',
    era: 'active',
    url: 'https://www.hedtags.org',
    summary: 'Maintains Hierarchical Event Descriptors (HED), the event annotation standard used with BIDS.',
  },
  {
    id: 'bids',
    name: 'Brain Imaging Data Structure (BIDS)',
    kind: 'standard',
    country: 'International',
    modalities: ['multisensory'],
    review: 'candidate',
    era: 'active',
    url: 'https://bids.neuroimaging.io',
    summary: 'Community standard for organising neuroimaging and behavioural data, including stimulus events.',
  },
  {
    id: 'incf',
    name: 'INCF',
    kind: 'organization',
    country: 'International',
    modalities: ['multisensory'],
    review: 'related',
    era: 'active',
    url: 'https://www.incf.org',
    summary: 'International neuroinformatics organisation that endorses standards and best practices.',
  },
  {
    id: 'itu-bt1702',
    name: 'ITU-R BT.1702',
    kind: 'standard',
    country: 'International',
    modalities: ['visual'],
    review: 'candidate',
    era: 'active',
    url: 'https://www.itu.int/rec/R-REC-BT.1702',
    summary: 'ITU recommendation on reducing the risk of photosensitive seizures from flashing television images.',
  },
  {
    id: 'psychopy',
    name: 'PsychoPy',
    kind: 'project',
    country: 'United Kingdom',
    modalities: ['visual', 'auditory'],
    review: 'candidate',
    era: 'active',
    url: 'https://www.psychopy.org',
    summary: 'Open-source software for presenting precisely timed visual and auditory stimuli in experiments.',
  },
  {
    id: 'psychtoolbox',
    name: 'Psychtoolbox',
    kind: 'project',
    country: 'International',
    modalities: ['visual', 'auditory'],
    review: 'candidate',
    era: 'active',
    url: 'https://psychtoolbox.org',
    summary: 'Open-source toolbox for precise visual and auditory stimulus presentation in MATLAB and Octave.',
  },
  {
    id: 'sbagen',
    name: 'SBaGen',
    kind: 'project',
    country: 'United Kingdom',
    modalities: ['auditory'],
    review: 'candidate',
    era: 'past',
    url: 'https://uazu.net/sbagen/',
    summary: 'Open-source sequenced binaural beat generator by Jim Peters, from the early 2000s.',
  },
  {
    id: 'dreamachine-2022',
    name: 'Dreamachine (Collective Act)',
    kind: 'project',
    country: 'United Kingdom',
    modalities: ['visual', 'auditory'],
    review: 'candidate',
    era: 'past',
    url: 'https://dreamachine.world',
    summary: 'Public art and science project (2022) offering a collective flicker experience with the eyes closed, with research on perceptual diversity.',
  },
]
