#!/usr/bin/env python3
"""Generate the term tables of a release's migration guide.

    python3 scripts/generate-migration-guide.py 0.18.0 0.19.0          write
    python3 scripts/generate-migration-guide.py 0.18.0 0.19.0 --check  fail if stale

The guide is docs/ontology/MIGRATING_TO_<to>.md. Its prose is written by hand;
the tables between the BEGIN/END markers are generated here from the ontology
itself, so the list an adopter follows is the list the release deprecates, with
the successor each term names in `dct:isReplacedBy` or the reason its
`skos:historyNote` gives for having none.

The comparison is the frozen `<from>` release against the frozen `<to>` release
when that exists, and against the live modules before it is cut. So the check
holds the guide to the release while it is prepared and stays true after it,
when the live line has moved on.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

from rdflib import Graph, OWL, RDF, URIRef
from rdflib.namespace import DCTERMS, SKOS

ROOT = Path(__file__).resolve().parents[1]
ONTOLOGY = ROOT / "static" / "ontology"
START = "<!-- BEGIN generated term tables -->"
END = "<!-- END generated term tables -->"

PREFIXES = {
    "https://w3id.org/sstim#": "sstim",
    "https://w3id.org/sstim/vocab#": "sstim-v",
    "https://w3id.org/sstim/exposure#": "sstim-ex",
    "https://w3id.org/sstim/ecosystem#": "sstim-eco",
    "https://w3id.org/sstim/shapes#": "sstim-sh",
    "https://w3id.org/sstim/framework/bsc/vocab#": "bsc-v",
    "http://purl.org/dc/terms/": "dct",
    "http://www.w3.org/ns/prov#": "prov",
}


def curie(term) -> str:
    text = str(term)
    for base, prefix in PREFIXES.items():
        if text.startswith(base):
            return f"{prefix}:{text[len(base):]}"
    return f"<{text}>"


def load(version: str, live_if_missing: bool = False) -> tuple[Graph, str]:
    frozen = ONTOLOGY / version
    if frozen.is_dir():
        manifest = json.loads((frozen / "manifest.json").read_text(encoding="utf-8"))
        paths = [frozen / Path(m["source"]["path"]).name for m in manifest["modules"]]
        source = f"frozen {version}"
    elif live_if_missing:
        manifest = json.loads((ONTOLOGY / "manifest.json").read_text(encoding="utf-8"))
        paths = [ROOT / m["source"]["path"] for m in manifest["modules"]]
        source = "the live modules"
    else:
        raise SystemExit(f"migration-guide: no frozen {version} release")
    graph = Graph()
    for path in paths:
        graph.parse(path, format="turtle")
    return graph, source


def deprecated(graph: Graph) -> set:
    return {
        s for s, o in graph.subject_objects(OWL.deprecated)
        if isinstance(s, URIRef) and str(o).lower() == "true"
    }


def kind(graph: Graph, term) -> str:
    types = set(graph.objects(term, RDF.type))
    if SKOS.ConceptScheme in types:
        return "scheme"
    if SKOS.Concept in types:
        return "concept"
    if OWL.Class in types:
        return "class"
    return "property"


def no_replacement_reason(graph: Graph, term) -> str:
    for note in graph.objects(term, SKOS.historyNote):
        text = " ".join(str(note).split())
        if re.search(r"\bno (?:single )?replacement\b", text, re.IGNORECASE):
            return text.replace("|", "\\|")
    return ""


def tables(old: Graph, new: Graph, source: str, previous: str, version: str) -> str:
    newly = sorted(deprecated(new) - deprecated(old), key=curie)
    gained = sorted(
        (t for t in deprecated(old) if list(new.objects(t, DCTERMS.isReplacedBy))
         and not list(old.objects(t, DCTERMS.isReplacedBy))),
        key=curie,
    )
    groups = {
        "Moved to the BSC framework vocabulary": [],
        "Replaced by other SSTIM terms": [],
        "Deprecated with no replacement": [],
    }
    for term in newly:
        successors = sorted(new.objects(term, DCTERMS.isReplacedBy), key=curie)
        if not successors:
            groups["Deprecated with no replacement"].append(term)
        elif all(curie(s).startswith("bsc-v:") for s in successors):
            groups["Moved to the BSC framework vocabulary"].append(term)
        else:
            groups["Replaced by other SSTIM terms"].append(term)

    lines = [
        START,
        "",
        f"*Generated by `scripts/generate-migration-guide.py {previous} {version}` from the frozen "
        f"{previous} release and {source}. Do not edit; rerun it.*",
        "",
        f"{len(newly)} terms are newly deprecated in {version}.",
    ]
    for heading, terms in groups.items():
        if not terms:
            continue
        lines += ["", f"### {heading} ({len(terms)})", ""]
        if heading == "Deprecated with no replacement":
            lines += ["| Deprecated | Kind | Why |", "|---|---|---|"]
            for term in terms:
                lines.append(f"| `{curie(term)}` | {kind(new, term)} | {no_replacement_reason(new, term)} |")
        else:
            lines += ["| Deprecated | Kind | Replaced by |", "|---|---|---|"]
            for term in terms:
                successors = ", ".join(f"`{curie(s)}`" for s in sorted(new.objects(term, DCTERMS.isReplacedBy), key=curie))
                lines.append(f"| `{curie(term)}` | {kind(new, term)} | {successors} |")
    if gained:
        lines += [
            "",
            f"### Earlier deprecations that now name their successor ({len(gained)})",
            "",
            f"Deprecated before {version}; {version} adds the `dct:isReplacedBy` their definitions "
            "already described.",
            "",
            "| Deprecated | Kind | Replaced by |",
            "|---|---|---|",
        ]
        for term in gained:
            successors = ", ".join(f"`{curie(s)}`" for s in sorted(new.objects(term, DCTERMS.isReplacedBy), key=curie))
            lines.append(f"| `{curie(term)}` | {kind(new, term)} | {successors} |")
    lines += ["", END]
    return "\n".join(lines)


def main() -> int:
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    if len(args) != 2:
        raise SystemExit("usage: generate-migration-guide.py <from-version> <to-version> [--check]")
    previous, version = args
    guide = ROOT / "docs" / "ontology" / f"MIGRATING_TO_{version}.md"
    text = guide.read_text(encoding="utf-8")
    if text.count(START) != 1 or text.count(END) != 1:
        raise SystemExit(f"migration-guide: {guide.relative_to(ROOT)} needs exactly one {START} ... {END} region")
    old, _ = load(previous)
    new, source = load(version, live_if_missing=True)
    region = tables(old, new, source, previous, version)
    updated = text.split(START, 1)[0] + region + text.split(END, 1)[1]
    if "--check" in sys.argv:
        if updated != text:
            print(
                f"migration-guide: STALE, {guide.relative_to(ROOT)} no longer matches what {version} "
                f"deprecates. Run `python3 scripts/generate-migration-guide.py {previous} {version}`.",
                file=sys.stderr,
            )
            return 1
        print(f"migration-guide: {guide.relative_to(ROOT)} matches {source}")
        return 0
    guide.write_text(updated, encoding="utf-8")
    print(f"migration-guide: wrote {guide.relative_to(ROOT)} from {source}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
